### ISSUE TITLE
"Improper file format" when importing Coredata Mii

### ISSUE THREAD

**Issue by clamintus** [Genwald/MiiPort#5]
The app fails to import my Coredata Mii, displaying the error mentioned in the title.
The Mii in question is directly extracted from RFL_DB.dat, which is the Mii archive stored in the Wii's NAND, and as such its size is 0x4A.

**Comment by Genwald** [comment]
The Miis on the Wii are stored in a different format. This tool currently supports only the version of the coredata format that is used on the Switch. Currently it is only planned to support importing from from previous Mii formats through QR code.

**Comment by clamintus** [comment]
Oh, sorry for the trouble, I was confused by the name being similar to "Revolution Core Data", which is the Mii format for Miis stored in Wii games and I actually thought they were the same.
Could I know if there is a way to import Wii Miis to Switch then? I tried to search for converters on the web, but I haven't found anything useful.

**Comment by Genwald** [comment]
Unfortunately, I don't know of any converter tool. I think there are official ways to transfer them from Wii to Wii U or 3DS though. That is the best option that I know of.
