### ISSUE TITLE
MiiDatabase.dat not recognized

### ISSUE THREAD

**Issue by TheJoigoMan** [Genwald/MiiPort#8]
Hello,

My old switch emunand killed my sd card and I managed to extract my old MiiDatabase.dat.
I'm trying to inject it to the new Emunand, but the app keeps telling me that there is a "Improper file format".
I am attaching the file and the new database extracted from the new emunand
[Databases.zip](https://github.com/Genwald/MiiPort/files/11493819/Databases.zip)

**Comment by Genwald** [comment]
That old DB looks like NFDB format. Did you extract that directly from nand/emunand? MiiPort Doesn't currently support importing that format. But the NFDB format is made up of Miis in the StoreData format, which is supported for import. They could be manually extracted if you want them recovered. I didn't test to make sure I didn't mess anything up, but this should be the first two Miis from that old DB.

[GH_issues_mii_storedata.zip](https://github.com/Genwald/MiiPort/files/11594370/GH_issues_mii_storedata.zip)
